### ISSUE TITLE
error executing the program please help

### ISSUE THREAD

**Issue by h1d30us** [TheDeGeO/Bomberman-CE#1]
navi$ python bomberman.py
Traceback (most recent call last):
  File "/home/anon/Documents/Bomberman-CE/bomberman.py", line 1, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'

what to do bro

**Comment by lVoidi** [comment]
Same thing happened to me, i am waiting for the solution :/

**Comment by TheDeGeO** [comment]
```
paru -S python-pygame
```

**Comment by h1d30us** [comment]
> ```
> paru -S python-pygame
> ```

navi$ paru -S python-pygame
/bin/oksh: paru: not found


error not fixed :/

**Comment by lVoidi** [comment]
Does it work with windows
> paru -S python-pygame

**Comment by TheDeGeO** [comment]
> > ```
> > paru -S python-pygame
> > ```
> 
> navi$ paru -S python-pygame
> /bin/oksh: paru: not found
> 
> 
> error not fixed :/
> 


```
sudo pacman -S --needed base-devel git
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
```

**Comment by h1d30us** [comment]
navi$ sudo pacman -S --needed base-devel git
Password:
sudo: pacman: command not found

:////

**Comment by lVoidi** [comment]
it says sudo is not recognized how fix

सुडो: 'सुडो' शब्द को सीएमडीलेट, फ़ंक्शन, स्क्रिप्ट फ़ाइल या निष्पादन योग्य प्रोग्राम के नाम के रूप में पहचाना नहीं जाता है।
जांचें कि क्या आपने नाम सही ढंग से टाइप किया है या, यदि आपने कोई पथ शामिल किया है, तो जांचें कि पथ सही है और
पुनः प्रयास करें।
ऑनलाइन: 1 चरित्र: 1
+ सुडो पैक्मैन -एस - बेस-डेवेल गिट की आवश्यकता है
+ ~~~~
    + कैटेगरीइन्फो: ऑब्जेक्टनॉटफाउंड: (सुडो:स्ट्रिंग) [], कमांडनॉटफाउंडएक्सेप्शन
    + FullyQualifiedErrorId: CommandNotFoundException

**Comment by h1d30us** [comment]
> it says sudo is not recognized how fix
> 
> सुडो: 'सुडो' शब्द को सीएमडीलेट, फ़ंक्शन, स्क्रिप्ट फ़ाइल या निष्पादन योग्य प्रोग्राम के नाम के रूप में पहचाना नहीं जाता है। जांचें कि क्या आपने नाम सही ढंग से टाइप किया है या, यदि आपने कोई पथ शामिल किया है, तो जांचें कि पथ सही है और पुनः प्रयास करें। ऑनलाइन: 1 चरित्र: 1
> 
>     * सुडो पैक्मैन -एस - बेस-डेवेल गिट की आवश्यकता है
> 
>     * ```
>         + कैटेगरीइन्फो: ऑब्जेक्टनॉटफाउंड: (सुडो:स्ट्रिंग) [], कमांडनॉटफाउंडएक्सेप्शन
>         + FullyQualifiedErrorId: CommandNotFoundException
>       ```

हेलो भाई आप भी भारतवासी हो

**Comment by TheDeGeO** [comment]
> Does it work with windows
> > paru -S python-pygame
> 

```
choco install paru
```

**Comment by h1d30us** [comment]
![image](https://github.com/user-attachments/assets/9a93b841-5c20-49f8-bee5-15178c6bfd6f)

**Comment by lVoidi** [comment]
> > Does it work with windows
> > > paru -S python-pygame
> 
> ```
> choco install paru
> ```

Thanks brother is now windows working

**Comment by h1d30us** [comment]
is liinux working too brother thanks yes
